name: Deploy starwarsstore Server

on: 
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_DO_TOKEN: ${{ secrets.DO_TOKEN  }}
  TF_VAR_DB_CLUSTER: ${{ secrets.DB_CLUSTER }}
  TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  TF_VAR_DB_USER: ${{ secrets.DB_USER }}
  TF_VAR_DOMAIN: ${{ secrets.DOMAIN }}
  TF_VAR_API_DOMAIN: ${{ secrets.API_DOMAIN }}
  TF_VAR_USER_EMAIL: ${{ secrets.USER_EMAIL }}
  TF_VAR_MONGO_URI: ${{ secrets.MONGO_URI }}
  TF_VAR_DB_NAME: ${{ secrets.DB_NAME }}




jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Create SSH Keys from secrets
        run: |
            mkdir keys
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/api-tienda-keys
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/api-tienda-keys.pub
            chmod 777 ./keys/api-tienda-keys
            chmod 777 ./keys/api-tienda-keys.pub
      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve

